{% set name = "docformatter" %}
{% set version = "1.7.5" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffed3da0daffa2e77f80ccba4f0e50bfa2755e1c10e130102571c890a61b246e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - docformatter = docformatter.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - charset-normalizer >=3.0.0
    - python >={{ python_min }}
    - untokenize >=0.1.1

test:
  requires:
    - python {{ python_min }}
  commands:
    - docformatter -h

about:
  home: https://github.com/myint/docformatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Formats docstrings to follow `PEP 257 <https://www.python.org/dev/peps/pep-0257/>`_.
  description: |
    docformatter currently automatically formats docstrings to follow a subset of the PEP 257 conventions.
  dev_url: https://github.com/myint/docformatter

extra:
  recipe-maintainers:
    - weiji14
    - carlodri
