{% set name = "docformatter" %}
{% set version = "1.7.8" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6589b62a8f38c62c4c8c84cb1afa296af007c88c959e4c9d25c74c1f933c4dbf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - docformatter = docformatter.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - charset-normalizer >=3.0.0
    - python >={{ python_min }}
    - untokenize >=0.1.1

test:
  requires:
    - python {{ python_min }}
  commands:
    - docformatter -h

about:
  home: https://github.com/myint/docformatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Formats docstrings to follow `PEP 257 <https://www.python.org/dev/peps/pep-0257/>`_.
  description: |
    docformatter currently automatically formats docstrings to follow a subset of the PEP 257 conventions.
  dev_url: https://github.com/myint/docformatter

extra:
  recipe-maintainers:
    - weiji14
    - carlodri
