{% set name = "docformatter" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34644db7d9781bde65a729c023940de26b61a39e3432eb35e9de3ddfe25d740a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - docformatter = docformatter.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
  run:
    - charset-normalizer >=3.0.0
    - python >=3.7
    - untokenize >=0.1.1

test:
  commands:
    - docformatter -h

about:
  home: https://github.com/myint/docformatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Formats docstrings to follow `PEP 257 <https://www.python.org/dev/peps/pep-0257/>`_.
  description: |
    docformatter currently automatically formats docstrings to follow a subset of the PEP 257 conventions. 
  dev_url: https://github.com/myint/docformatter

extra:
  recipe-maintainers:
    - weiji14
    - carlodri
